version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached

    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - redis
    network_mode: service:redis

  redis:
    image: redis
    restart: always
    volumes:
      - cache:/data/redis
    ports:
      - "6379:6379"

volumes:
  cache:
